fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    mkdir: "https://github.com/flypenguin/puppet-mkdir.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"

  symlinks:
    talend_administration_center: "#{source_dir}"
